### PR TITLE
Move mocha and should to dev dependencies

### LINKED ISSUE #285: mocha and dependencies
Why is mocha in dependencies and not devDependencies (or why is mocha version emoty string there ?)

### PR DESCRIPTION
**Pull request by MartijnCuppens**
It looks like `mocha` and `should` were accidently moved the dependencies (see https://github.com/jkphl/svg-sprite/commit/b9a2df3702d6f7322d6f0bc3df2edcdab88a9a14). This PR moves them back to the dev dependencies.

Closes #285

### CODE REVIEW

**Comment by hiroshi** [comment]
This will fix https://github.com/jkphl/svg-sprite/issues/285.

**Comment by ogonkov** [comment]
@jkphl ?

**Comment by MartijnCuppens** [comment]
Btw, the `package-lock.json` should also be regenerated, otherwise this change has no effect.

**Comment by jkphl** [comment]
@MartijnCuppens I'm still testing, merging other PRs and doing some updates. `package-json.lock` will be updated as soon as I push out a new release, please bear with me.

**Comment by MartijnCuppens** [comment]
Thanks, I noticed you also enabled dependabot, nice. Keep up the good work 💪

**Comment by jkphl** [comment]
@MartijnCuppens Unfortunately, I almost can't find any capacity to care for my OS projects in the last one-two years. Thanks for your support and apologies for the loooooong delays!

**Comment by G-Rath** [comment]
@jkphl any chance this could get published as a patch for the 1.5.x line?

A security vulnerability was recently discovered in `mkdirp` , which is used by `mocha` 5.2.0 via an exact constraint, meaning our security scanners are flagging it via `svg-sprite`.

Just publishing a new version of `svg-sprite` with `mocha` as a devDependency should fix this. I'm going to ask mocha if they would be open to backporting the update, but given they're up on v8 I don't like the chances 😬

Happy to help if possible!

**Pull request merged**
