### PR TITLE
fix typo on configuration.md

### PR DESCRIPTION
**Pull request by tgfjt**

### CODE REVIEW

**Comment by jkphl** [comment]
どうもすみません, but the term *prolyfill* has been chosen [intentionally](https://au.si/what-is-a-prolyfill). ;)

**Comment by jkphl** [comment]
@tgfjt One question though: Are you actively using svg stacks as described in that part of the documentation?

**Comment by tgfjt** [comment]
Oh I see. sorry, my bad!

I just use symbols now.
I wonder if I should use defs or symbols or stacks... Is it stacks good??

**Comment by jkphl** [comment]
@tgfjt I'd stick to symbols as well! :)

Personally I don't think stacks are the way to go. I was just wondering if anybody is using them at all. I'm planning a new major release and am thinking about dropping support completely ...

**Comment by tgfjt** [comment]
I agree with dropping support.
We want simple and stable way!

**Pull request closed without merging**
